
export async function fight(req, res) {
    
    try{
      
    }catch(error){
      res.status(400).send(error)
    }
}

export async function signIn(req, res) {
  
  try{
   

  }catch(error){
    console.log(error)
    res.sendStatus(400)
  }
}
